<?php

/**
 * Global Config File — AUTO-GENERATED BY CORTEXO
 *
 * Template version: 4.2.0
 * Generated at: {{GENERATED_AT}}
 * Client: {{CLIENT_SLUG}}
 *
 * ⚠️  DO NOT EDIT MANUALLY — changes will be overwritten on next deploy.
 *     Use Cortexo Dashboard → Sources → Client Config to modify values.
 *
 * @author  Logimax Team
 */

// Prevent direct script access
if (isset($_SERVER['REQUEST_METHOD']) && $_SERVER['REQUEST_METHOD'] == 'GET' && realpath(__FILE__) == realpath($_SERVER['SCRIPT_FILENAME'])) {
	header("HTTP/1.0 404 Not Found");
	echo "<h1>Not Found</h1>";
	echo "The requested URL was not found on this server.";
	exit();
}

/**
 * Global Constants Class
 */
class Globals
{
    // ─── Identity ───────────────────────────────────────────────────────────────

    /** Website version */
    public static $web_version = "{{VERSIONS.WEB_VERSION|1.0.1}}";

    /** Admin version */
    public static $admin_web_version = "{{VERSIONS.ADMIN_WEB_VERSION|4.2.0}}";

    /** Android version names */
    public static $VERSIONNAME         = '{{VERSIONS.VERSIONNAME|1.0.0}}';
    public static $NEWVERSIONNAME      = '{{VERSIONS.NEWVERSIONNAME|1.0.0}}';
    public static $CURRENTVERSIONNAME  = '{{VERSIONS.CURRENTVERSIONNAME|1.0.0}}';

    /** iOS version names */
    public static $IOSVERSIONNAME         = '{{VERSIONS.IOSVERSIONNAME|1.0.0}}';
    public static $IOSNEWVERSIONNAME      = '{{VERSIONS.IOSNEWVERSIONNAME|1.0.0}}';
    public static $IOSCURRENTVERSIONNAME  = '{{VERSIONS.IOSCURRENTVERSIONNAME|1.0.0}}';

    /** OTR flags */
    public static $IOS_OTR      = {{FLAGS.IOS_OTR|0}};
    public static $ANDROID_OTR  = {{FLAGS.ANDROID_OTR|0}};

    /** User Account Delete */
    public static $IOS_USERDELETE      = {{FLAGS.IOS_USERDELETE|0}};
    public static $ANDROID_USERDELETE  = {{FLAGS.ANDROID_USERDELETE|0}};

    // ─── URLs ───────────────────────────────────────────────────────────────────

    /** Base URLs */
    public static $web_base_url   = "{{URLS.WEB_BASE_URL}}";
    public static $app_base_url   = "{{URLS.APP_BASE_URL}}";
    public static $admin_base_url = "{{URLS.ADMIN_BASE_URL}}";

    // ─── Database ───────────────────────────────────────────────────────────────

    /** Database credentials */
    public static $hostname = "{{DATABASE.HOSTNAME}}";
    public static $username = "{{DATABASE.USERNAME}}";
    public static $password = "{{DATABASE.PASSWORD}}";
    public static $database = "{{DATABASE.DATABASE}}";

    // ─── Website Details ────────────────────────────────────────────────────────

    /** Website details */
    public static $web_title     = "{{IDENTITY.WEB_TITLE}}";
    public static $web_copyright = "{{IDENTITY.WEB_COPYRIGHT|© 2026 {{IDENTITY.WEB_TITLE}}. All Rights Reserved}}";

    /** Client information */
    public static $client = "{{IDENTITY.CLIENT}}";

    // ─── Socket Config ──────────────────────────────────────────────────────────

    /** Socket details */
    public static $socket_base_url = "{{SOCKET.SOCKET_BASE_URL|{{URLS.WEB_BASE_URL}}}}";
    public static $rate_socketurl  = "{{SOCKET.RATE_SOCKETURL|{{URLS.WEB_BASE_URL}}ratesocket/socket.io}}";

    // ─── Lightstreamer ──────────────────────────────────────────────────────────

    /** LS connection details */
    public static $lsrateurl           = "{{LIGHTSTREAMER.LSRATEURL|http://72.52.178.11:8080}}";
    public static $lsrateadapter       = "{{LIGHTSTREAMER.LSRATEADAPTER|WLSTOCKLIST_REMOTE}}";
    public static $lsrateprovider      = "{{LIGHTSTREAMER.LSRATEPROVIDER|WLQUOTE_ADAPTER}}";
    public static $lsrateusername      = "{{LIGHTSTREAMER.LSRATEUSERNAME|lmxwinbullliteapp}}";
    public static $lsrateusernameapp   = "{{LIGHTSTREAMER.LSRATEUSERNAMEAPP|lmxwinbullliteapp}}";

    // ─── API Endpoints ──────────────────────────────────────────────────────────

    /** API endpoints */
    public static $rateurl = "{{URLS.WEB_BASE_URL}}lmxtrade/winbullliteapi/api/v1/wlcurrentrates";

    // ─── Broadcast Rate Config ──────────────────────────────────────────────────

    /** Broadcast Rate Details */
    public static $rpbcencdata = "{{URLS.WEB_BASE_URL}}index.php/C_rates/rp_rate_data";
    public static $bcencdata   = "{{URLS.WEB_BASE_URL}}index.php/C_rates/rate_data";
    public static $txtdata     = "{{URLS.WEB_BASE_URL}}client/logimax.txt";
    public static $rp_txtdata  = "{{URLS.WEB_BASE_URL}}client/logimax.txt";
    public static $bcurl       = "{{URLS.WEB_BASE_URL}}lmxtrade/winbullliteapi/api/v1/broadcastrates";
    public static $bcsrurl     = "{{URLS.WEB_BASE_URL}}lmxtrade/winbullliteapi/api/v1/broadcastsourcerates";
    public static $ratesocketurl = "{{SOCKET.RATESOCKETURL|{{URLS.WEB_BASE_URL}}}}";
    public static $nativesocketurl = "{{SOCKET.NATIVESOCKETURL|ws://{{IDENTITY.CLIENT_DOMAIN}}/ws}}";

    public static $bcclient    = "{{BROADCAST.BCCLIENT|{{IDENTITY.CLIENT}}}}";
    public static $bcusername  = "{{BROADCAST.BCUSERNAME|{{IDENTITY.CLIENT}}}}";
    public static $bcpassword  = "{{BROADCAST.BCPASSWORD|{{IDENTITY.CLIENT}}-trade}}";
    public static $bcupdatetime = "{{BROADCAST.BCUPDATETIME|800}}";

    // ─── Rate Feed Type ─────────────────────────────────────────────────────────

    /** Data types and flags */
    public static $bcrateType = {{RATEFEED.BCRATETYPE|2}};   // 0-> normal(php) 1-> encryption(php)   2-> websocket // Web
    public static $app_header_chk = {{FLAGS.APP_HEADER_CHK|0}};
    public static $rpRateType   = {{RATEFEED.RPRATETYPE|0}};  // 0=PHP encryption, 1=websocket  (For Rpanel)
    public static $rateFeed = {{RATEFEED.RATEFEED|4}};  // 0-> encryption(php) 1-> broadcastrate 2-> text file 3-> Web socket 4-> Native Socket // App
    public static $polling = {{FLAGS.POLLING|1}};   // 0-> off 1-> on
    public static $websocket_type = {{RATEFEED.WEBSOCKET_TYPE|2}};  // 1-> socket.io 2-> Native socket

    // ─── Encryption ─────────────────────────────────────────────────────────────

    /** Encryption Key */
    public static $key = '{{ENCRYPTION.KEY}}';

    /** Path to encrypted file */
    public static $path = "{{ENCRYPTION.PATH|/var/www/html/{{IDENTITY.CLIENT}}/client/{{IDENTITY.CLIENT}}.enc}}";

    // ─── Socket Event URLs (auto-generated from client + base URL) ──────────────

    /** Socket Event URLs */
    public static $commodityupdate         = "{{URLS.WEB_BASE_URL}}lmxtrade/winbullliteapi/api/v1/{{IDENTITY.CLIENT}}commoditygroupupdate";
    public static $rpanelupdate            = "{{URLS.WEB_BASE_URL}}lmxtrade/winbullliteapi/api/v1/{{IDENTITY.CLIENT}}rpanelupdate";
    public static $newsupdate              = "{{URLS.WEB_BASE_URL}}lmxtrade/winbullliteapi/api/v1/{{IDENTITY.CLIENT}}newsupdate";
    public static $marqueeupdate           = "{{URLS.WEB_BASE_URL}}lmxtrade/winbullliteapi/api/v1/{{IDENTITY.CLIENT}}marqueeupdate";
    public static $createratealert         = "{{URLS.WEB_BASE_URL}}lmxtrade/winbullliteapi/api/v1/wlcreateratealert";
    public static $updateratealert         = "{{URLS.WEB_BASE_URL}}lmxtrade/winbullliteapi/api/v1/wlupdateratealert";
    public static $cancelratealert         = "{{URLS.WEB_BASE_URL}}lmxtrade/winbullliteapi/api/v1/wlremoveratealert";
    public static $clearallratealert       = "{{URLS.WEB_BASE_URL}}lmxtrade/winbullliteapi/api/v1/wlremoveclientratealerts";
    public static $bookupdate              = "{{URLS.WEB_BASE_URL}}lmxtrade/winbullliteapi/api/v1/{{IDENTITY.CLIENT}}bookupdate";
    public static $limitupdate             = "{{URLS.WEB_BASE_URL}}lmxtrade/winbullliteapi/api/v1/{{IDENTITY.CLIENT}}limitupdate";
    public static $settingsupdate          = "{{URLS.WEB_BASE_URL}}lmxtrade/winbullliteapi/api/v1/wlupdateclienttrade";
    public static $getrates                = "{{URLS.WEB_BASE_URL}}lmxtrade/winbullliteapi/api/v1/wlclientsrates";
    public static $clientdetails           = "{{URLS.WEB_BASE_URL}}lmxtrade/winbullliteapi/api/v1/wlclientdetails";
    public static $createclient            = "{{URLS.WEB_BASE_URL}}lmxtrade/winbullliteapi/api/v1/wlcreateclient";
    public static $terminateuser           = "{{URLS.WEB_BASE_URL}}lmxtrade/winbullliteapi/api/v1/{{IDENTITY.CLIENT}}terminateuserupdate";

    // ─── Socket Events (auto-generated from client name) ────────────────────────

    /** Socket Events */
    public static $evt_commupdate        = "{{IDENTITY.CLIENT}}updatecommodity:App\\Events\\{{IDENTITY.CLIENT_UPPER}}CommodityUpdates";
    public static $evt_rpanelupdate       = "{{IDENTITY.CLIENT}}updatepanel:App\\Events\\{{IDENTITY.CLIENT_UPPER}}RpanelUpdates";
    public static $evt_bookupdate        = "{{IDENTITY.CLIENT}}updatebook:App\\Events\\{{IDENTITY.CLIENT_UPPER}}BookUpdates";
    public static $evt_limitupdate        = "{{IDENTITY.CLIENT}}updatelimit:App\\Events\\{{IDENTITY.CLIENT_UPPER}}LimitUpdates";
    public static $evt_trdstatusupdate  = "wltradeupdate:App\\Events\\WLTradeStatusUpdate";
    public static $evt_marqueeupdate    = "{{IDENTITY.CLIENT}}updatemarquee:App\\Events\\{{IDENTITY.CLIENT_UPPER}}MarqueeUpdates";
    public static $evt_newsupdate        = "{{IDENTITY.CLIENT}}updatenews:App\\Events\\{{IDENTITY.CLIENT_UPPER}}NewsUpdates";
    public static $evt_textupdate         = "{{IDENTITY.CLIENT}}updatetext:App\\Events\\{{IDENTITY.CLIENT_UPPER}}TextUpdates";
    public static $evt_terminateuser    = "{{IDENTITY.CLIENT}}updateusertermination:App\\Events\\{{IDENTITY.CLIENT_UPPER}}UserUpdates";

    // ─── Notifications ──────────────────────────────────────────────────────────

    /** Notification Settings */
    public static $notification_title             = "{{NOTIFICATIONS.NOTIFICATION_TITLE|{{IDENTITY.WEB_TITLE}}}}";
    public static $notification_subtitle          = "{{NOTIFICATIONS.NOTIFICATION_SUBTITLE|From {{IDENTITY.WEB_TITLE}}}}";
    public static $onesignalAPI                   = "https://onesignal.com/api/v1/notifications";
    public static $app_id                         = "{{NOTIFICATIONS.APP_ID}}";
    public static $onesignalauth                  = "{{NOTIFICATIONS.ONESIGNALAUTH}}";
    public static $notification_title_admin       = "{{NOTIFICATIONS.NOTIFICATION_TITLE_ADMIN|{{IDENTITY.WEB_TITLE}} Admin App}}";
    public static $notification_subtitle_admin     = "{{NOTIFICATIONS.NOTIFICATION_SUBTITLE_ADMIN|From {{IDENTITY.WEB_TITLE}} Admin App}}";
    public static $app_id_admin                   = "{{NOTIFICATIONS.APP_ID_ADMIN}}";
    public static $onesingalapi_admin             = "{{NOTIFICATIONS.ONESINGALAPI_ADMIN}}";

    // ─── WhatsApp ───────────────────────────────────────────────────────────────

    /** WhatsApp Configuration */
    public static $whatsappurl = "{{WHATSAPP.WHATSAPPURL|http://whatsappsms.creativepoint.in/api/}}";
    public static $instanceid  = "{{WHATSAPP.INSTANCEID}}";

    // ─── Mobile App Store URLs ──────────────────────────────────────────────────

    /** Mobile App URLs */
    public static $androidUrl = "{{MOBILEAPPS.ANDROIDURL}}";
    public static $iosUrl     = "{{MOBILEAPPS.IOSURL}}";

    // ─── Email ──────────────────────────────────────────────────────────────────

    /** Enquiry Email IDs */
    public static $enqFromId = "{{EMAIL.ENQFROMID}}";
    public static $enqToId   = "{{EMAIL.ENQTOID}}";
    public static $enqCCId   = "{{EMAIL.ENQCCID}}";

    // ─── Display ────────────────────────────────────────────────────────────────

    /** Book Number Placeholder */
    public static $bookno_for_mobile = '{{DISPLAY.BOOKNO_FOR_MOBILE}}';

    // ─── Timezone ───────────────────────────────────────────────────────────────

    /** Timezone */
    public static $timezone = "{{IDENTITY.TIMEZONE|Asia/Kolkata}}";

    // ─── Hedge Config ───────────────────────────────────────────────────────────

    /** Motilal Oswal Hedge Configuration */
    public static $clientcode = "{{HEDGE.CLIENTCODE}}";
    public static $hedge_password = "{{HEDGE.HEDGE_PASSWORD}}";
    public static $secret_key = "{{HEDGE.SECRET_KEY}}";
    public static $twoFA = "{{HEDGE.TWOFA}}";
    public static $ApiKey = "{{HEDGE.APIKEY}}";
    public static $authapi = "{{HEDGE.AUTHAPI}}";
    public static $placeorder = "{{HEDGE.PLACEORDER}}";
    public static $gold_mini_symbol = "{{HEDGE.GOLD_MINI_SYMBOL}}";
    public static $gold_micro_symbol = "{{HEDGE.GOLD_MICRO_SYMBOL}}";
}

// Set default timezone
date_default_timezone_set(Globals::$timezone);

// Check cURL
if (!function_exists('curl_version')) {
    exit("Enable cURL in PHP to proceed...");
}

// ─── Cortexo Error Tracking SDK ─────────────────────────────────────────────
// Auto-captures PHP errors, exceptions, and fatal crashes.
// Errors appear in Cortexo Dashboard → Errors within seconds.
$__cortexo_sdk = __DIR__ . '/cortexo-sdk.php';
if (file_exists($__cortexo_sdk)) {
    require_once $__cortexo_sdk;
    CortexoSDK::init([
        'apiKey'      => '{{CORTEXO.API_KEY}}',
        'endpoint'    => '{{CORTEXO.ENDPOINT|http://localhost:4000/v1/ingest/error}}',
        'client'      => Globals::$client,
        'environment' => '{{CORTEXO.ENVIRONMENT|production}}',
        'release'     => Globals::$admin_web_version,
        'enabled'     => {{CORTEXO.ENABLED|true}},
    ]);
}
