<?php

/**
 * Global Config File - {{DISPLAY_NAME}}
 * 
 * Generated by WinBull Config Generator
 * Date: {{GEN_DATE}}
 */

class Globals
{
    public static $web_version = "1.0.1";
    public static $admin_web_version = "4.2.0";

    public static $VERSIONNAME         = '1.0.0';
    public static $NEWVERSIONNAME      = '1.0.0';
    public static $CURRENTVERSIONNAME  = '1.0.0';

    public static $IOSVERSIONNAME         = '1.0.0';
    public static $IOSNEWVERSIONNAME      = '1.0.0';
    public static $IOSCURRENTVERSIONNAME  = '1.0.0';

    public static $IOS_OTR      = 0;
    public static $ANDROID_OTR  = 0;

    public static $IOS_USERDELETE      = 0;
    public static $ANDROID_USERDELETE  = 0;

    /** Base URLs */
    public static $web_base_url   = "{{WEB_URL}}";
    public static $app_base_url   = "{{WEB_URL}}mobileapi/";
    public static $admin_base_url = "{{WEB_URL}}admin/";

    /** Database credentials */
    public static $hostname = "{{DB_HOST}}";
    public static $username = "{{DB_USER}}";
    public static $password = "{{DB_PASS}}";
    public static $database = "{{DB_NAME}}";

    /** Website details */
    public static $web_title     = "{{DISPLAY_NAME}}";
    public static $web_copyright = "© {{GEN_YEAR}} {{DISPLAY_NAME}}. All Rights Reserved";

    /** Client information */
    public static $client = "{{CLIENT_ID}}";

    /** Socket details */
    public static $socket_base_url = "{{WEB_URL}}";
    public static $rate_socketurl  = "{{WEB_URL}}ratesocket/socket.io";

    /** LS connection details */
    public static $lsrateurl           = "http://72.52.178.11:8080";
    public static $lsrateadapter       = "WLSTOCKLIST_REMOTE";
    public static $lsrateprovider      = "WLQUOTE_ADAPTER";
    public static $lsrateusername      = "lmxwinbullliteapp";
    public static $lsrateusernameapp   = "lmxwinbullliteapp";

    /** API endpoints */
    public static $rateurl = "{{WEB_URL}}lmxtrade/winbullliteapi/api/v1/wlcurrentrates";

    /** Broadcast Rate Details */
    public static $rpbcencdata = "{{WEB_URL}}index.php/C_rates/rp_rate_data";
    public static $bcencdata   = "{{WEB_URL}}index.php/C_rates/rate_data";
    public static $txtdata     = "{{WEB_URL}}client/logimax.txt";
    public static $rp_txtdata  = "{{WEB_URL}}client/logimax.txt";
    public static $bcurl       = "{{WEB_URL}}lmxtrade/winbullliteapi/api/v1/broadcastrates";
    public static $bcsrurl     = "{{WEB_URL}}lmxtrade/winbullliteapi/api/v1/broadcastsourcerates";
    public static $ratesocketurl = "{{WEB_URL}}";
    public static $nativesocketurl = "ws://{{DOMAIN}}/ws";

    public static $bcclient    = "{{CLIENT_ID}}";
    public static $bcusername  = "{{CLIENT_ID}}";
    public static $bcpassword  = "{{CLIENT_ID}}-trade";
    public static $bcupdatetime = "800";

    /** Data types and flags */
    public static $bcrateType = 2;
    public static $app_header_chk = 0;
    public static $rpRateType   = 0;
    public static $rateFeed = {{RATE_FEED_TYPE}};
    public static $polling = 1;
    public static $websocket_type = 2;

    /** Encryption Key */
    public static $key = '{{ENC_KEY}}';

    /** Path to encrypted file */
    public static $path = "/var/www/html/{{CLIENT_ID}}/client/{{CLIENT_ID}}.enc";

    /** Socket Event URLs */
    public static $commodityupdate         = "{{WEB_URL}}lmxtrade/winbullliteapi/api/v1/{{CLIENT_ID}}commoditygroupupdate";
    public static $rpanelupdate            = "{{WEB_URL}}lmxtrade/winbullliteapi/api/v1/{{CLIENT_ID}}rpanelupdate";
    public static $newsupdate              = "{{WEB_URL}}lmxtrade/winbullliteapi/api/v1/{{CLIENT_ID}}newsupdate";
    public static $marqueeupdate           = "{{WEB_URL}}lmxtrade/winbullliteapi/api/v1/{{CLIENT_ID}}marqueeupdate";
    public static $createratealert         = "{{WEB_URL}}lmxtrade/winbullliteapi/api/v1/wlcreateratealert";
    public static $updateratealert         = "{{WEB_URL}}lmxtrade/winbullliteapi/api/v1/wlupdateratealert";
    public static $cancelratealert         = "{{WEB_URL}}lmxtrade/winbullliteapi/api/v1/wlremoveratealert";
    public static $clearallratealert     = "{{WEB_URL}}lmxtrade/winbullliteapi/api/v1/wlremoveclientratealerts";
    public static $bookupdate              = "{{WEB_URL}}lmxtrade/winbullliteapi/api/v1/{{CLIENT_ID}}bookupdate";
    public static $limitupdate             = "{{WEB_URL}}lmxtrade/winbullliteapi/api/v1/{{CLIENT_ID}}limitupdate";
    public static $settingsupdate          = "{{WEB_URL}}lmxtrade/winbullliteapi/api/v1/wlupdateclienttrade";
    public static $getrates                = "{{WEB_URL}}lmxtrade/winbullliteapi/api/v1/wlclientsrates";
    public static $clientdetails           = "{{WEB_URL}}lmxtrade/winbullliteapi/api/v1/wlclientdetails";
    public static $createclient            = "{{WEB_URL}}lmxtrade/winbullliteapi/api/v1/wlcreateclient";
    public static $terminateuser        = "{{WEB_URL}}lmxtrade/winbullliteapi/api/v1/{{CLIENT_ID}}terminateuserupdate";

    /** Socket Events */
    public static $evt_commupdate        = "{{CLIENT_ID}}updatecommodity:App\\\Events\\\{{NAMESPACE}}CommodityUpdates";
    public static $evt_rpanelupdate       = "{{CLIENT_ID}}updaterpanel:App\\\Events\\\{{NAMESPACE}}RpanelUpdates";
    public static $evt_bookupdate        = "{{CLIENT_ID}}updatebook:App\\\Events\\\{{NAMESPACE}}BookUpdates";
    public static $evt_limitupdate        = "{{CLIENT_ID}}updatelimit:App\\\Events\\\{{NAMESPACE}}LimitUpdates";
    public static $evt_trdstatusupdate  = "wltradeupdate:App\\\Events\\\WLTradeStatusUpdate";
    public static $evt_marqueeupdate    = "{{CLIENT_ID}}updatemarquee:App\\\Events\\\{{NAMESPACE}}MarqueeUpdates";
    public static $evt_newsupdate        = "{{CLIENT_ID}}updatenews:App\\\Events\\\{{NAMESPACE}}NewsUpdates";
    public static $evt_textupdate         = "{{CLIENT_ID}}updatetext:App\\\Events\\\{{NAMESPACE}}TextUpdates";
    public static $evt_terminateuser    = "{{CLIENT_ID}}updateusertermination:App\\\Events\\\{{NAMESPACE}}UserUpdates";

    /** Notification Settings */
    public static $notification_title             = "{{DISPLAY_NAME}}";
    public static $notification_subtitle          = "From {{DISPLAY_NAME}}";
    public static $onesignalAPI                   = "https://onesignal.com/api/v1/notifications";
    public static $app_id                         = "{{ONESIGNAL_APP_ID}}";
    public static $onesignalauth                  = "{{ONESIGNAL_AUTH}}";
    public static $notification_title_admin       = "{{DISPLAY_NAME}} Admin App";
    public static $notification_subtitle_admin     = "From {{DISPLAY_NAME}} Admin App";
    public static $app_id_admin                   = "";
    public static $onesingalapi_admin             = "";

    /** WhatsApp Configuration */
    public static $whatsappurl = "http://whatsappsms.creativepoint.in/api/";
    public static $instanceid  = "";

    /** Mobile App URLs */
    public static $androidUrl = "";
    public static $iosUrl     = "";

    /** Enquiry Email IDs */
    public static $enqFromId = "";
    public static $enqToId   = "";
    public static $enqCCId   = "";

    /** Book Number Placeholder */
    public static $bookno_for_mobile = '<i class="phone-portrait"></i><a class="sub-color" href="tel:+{{COUNTRY_CODE}}"></a>';

    /** Timezone */
    public static $timezone = "{{TIMEZONE}}";

    /** Motilal Oswal Hedge Configuration (Only for Indian Clients) */
    public static $clientcode = "";
    public static $hedge_password = "";
    public static $secret_key = "";
    public static $twoFA = "";
    public static $ApiKey = "";
    public static $authapi = "";
    public static $placeorder = "";
    public static $gold_mini_symbol = "";
    public static $gold_micro_symbol = "";

    /** Currency Configuration */
    public static $currency_symbol = "{{CURRENCY_SYMBOL}}";
    public static $currency_name   = "{{CURRENCY_NAME}}";
}

// Set default timezone
date_default_timezone_set(Globals::$timezone);

// Check cURL
if (!function_exists('curl_version')) {
    exit("Enable cURL in PHP to proceed...");
}
