<?php

/**
 * Global Config File - KVT Jewellers
 * 
 * Generated by WinBull Config Generator
 * Date: 2026-05-04 12:04:58
 */

class Globals
{
    public static $web_version = "1.0.1";
    public static $admin_web_version = "4.2.0";

    public static $VERSIONNAME         = '1.0.0';
    public static $NEWVERSIONNAME      = '1.0.0';
    public static $CURRENTVERSIONNAME  = '1.0.0';

    public static $IOSVERSIONNAME         = '1.0.0';
    public static $IOSNEWVERSIONNAME      = '1.0.0';
    public static $IOSCURRENTVERSIONNAME  = '1.0.0';

    public static $IOS_OTR      = 0;
    public static $ANDROID_OTR  = 0;

    public static $IOS_USERDELETE      = 0;
    public static $ANDROID_USERDELETE  = 0;

    /** Base URLs */
    public static $web_base_url   = "http://stagingwt.kvtjewellers.com/";
    public static $app_base_url   = "http://stagingwt.kvtjewellers.com/mobileapi/";
    public static $admin_base_url = "http://stagingwt.kvtjewellers.com/admin/";

    /** Database credentials */
    public static $hostname = "database-1.cb86ugsw4aax.ap-south-1.rds.amazonaws.com";
    public static $username = "admin";
    public static $password = "admin2k25";
    public static $database = "kvt";

    /** Website details */
    public static $web_title     = "KVT Jewellers";
    public static $web_copyright = "© 2026 KVT Jewellers. All Rights Reserved";

    /** Client information */
    public static $client = "kvt";

    /** Socket details */
    public static $socket_base_url = "http://stagingwt.kvtjewellers.com/";
    public static $rate_socketurl  = "http://stagingwt.kvtjewellers.com/ratesocket/socket.io";

    /** LS connection details */
    public static $lsrateurl           = "http://72.52.178.11:8080";
    public static $lsrateadapter       = "WLSTOCKLIST_REMOTE";
    public static $lsrateprovider      = "WLQUOTE_ADAPTER";
    public static $lsrateusername      = "lmxwinbullliteapp";
    public static $lsrateusernameapp   = "lmxwinbullliteapp";

    /** API endpoints */
    public static $rateurl = "http://stagingwt.kvtjewellers.com/lmxtrade/winbullliteapi/api/v1/wlcurrentrates";

    /** Broadcast Rate Details */
    public static $rpbcencdata = "http://stagingwt.kvtjewellers.com/index.php/C_rates/rp_rate_data";
    public static $bcencdata   = "http://stagingwt.kvtjewellers.com/index.php/C_rates/rate_data";
    public static $txtdata     = "http://stagingwt.kvtjewellers.com/client/logimax.txt";
    public static $rp_txtdata  = "http://stagingwt.kvtjewellers.com/client/logimax.txt";
    public static $bcurl       = "http://stagingwt.kvtjewellers.com/lmxtrade/winbullliteapi/api/v1/broadcastrates";
    public static $bcsrurl     = "http://stagingwt.kvtjewellers.com/lmxtrade/winbullliteapi/api/v1/broadcastsourcerates";
    public static $ratesocketurl = "http://stagingwt.kvtjewellers.com/";
    public static $nativesocketurl = "ws://kvtjewellers.com/ws";

    public static $bcclient    = "kvt";
    public static $bcusername  = "kvt";
    public static $bcpassword  = "kvt-trade";
    public static $bcupdatetime = "800";

    /** Data types and flags */
    public static $bcrateType = 2;
    public static $app_header_chk = 0;
    public static $rpRateType   = 0;
    public static $rateFeed = 4;
    public static $polling = 1;
    public static $websocket_type = 2;

    /** Encryption Key */
    public static $key = '12@^tyh8901tt56789012345$y89012';

    /** Path to encrypted file */
    public static $path = "/var/www/html/kvt/client/kvt.enc";

    /** Socket Event URLs */
    public static $commodityupdate         = "http://stagingwt.kvtjewellers.com/lmxtrade/winbullliteapi/api/v1/kvtcommoditygroupupdate";
    public static $rpanelupdate            = "http://stagingwt.kvtjewellers.com/lmxtrade/winbullliteapi/api/v1/kvtrpanelupdate";
    public static $newsupdate              = "http://stagingwt.kvtjewellers.com/lmxtrade/winbullliteapi/api/v1/kvtnewsupdate";
    public static $marqueeupdate           = "http://stagingwt.kvtjewellers.com/lmxtrade/winbullliteapi/api/v1/kvtmarqueeupdate";
    public static $createratealert         = "http://stagingwt.kvtjewellers.com/lmxtrade/winbullliteapi/api/v1/wlcreateratealert";
    public static $updateratealert         = "http://stagingwt.kvtjewellers.com/lmxtrade/winbullliteapi/api/v1/wlupdateratealert";
    public static $cancelratealert         = "http://stagingwt.kvtjewellers.com/lmxtrade/winbullliteapi/api/v1/wlremoveratealert";
    public static $clearallratealert     = "http://stagingwt.kvtjewellers.com/lmxtrade/winbullliteapi/api/v1/wlremoveclientratealerts";
    public static $bookupdate              = "http://stagingwt.kvtjewellers.com/lmxtrade/winbullliteapi/api/v1/kvtbookupdate";
    public static $limitupdate             = "http://stagingwt.kvtjewellers.com/lmxtrade/winbullliteapi/api/v1/kvtlimitupdate";
    public static $settingsupdate          = "http://stagingwt.kvtjewellers.com/lmxtrade/winbullliteapi/api/v1/wlupdateclienttrade";
    public static $getrates                = "http://stagingwt.kvtjewellers.com/lmxtrade/winbullliteapi/api/v1/wlclientsrates";
    public static $clientdetails           = "http://stagingwt.kvtjewellers.com/lmxtrade/winbullliteapi/api/v1/wlclientdetails";
    public static $createclient            = "http://stagingwt.kvtjewellers.com/lmxtrade/winbullliteapi/api/v1/wlcreateclient";
    public static $terminateuser        = "http://stagingwt.kvtjewellers.com/lmxtrade/winbullliteapi/api/v1/kvtterminateuserupdate";

    /** Socket Events */
    public static $evt_commupdate        = "kvtupdatecommodity:App\\\Events\\\KVTCommodityUpdates";
    public static $evt_rpanelupdate       = "kvtupdaterpanel:App\\\Events\\\KVTRpanelUpdates";
    public static $evt_bookupdate        = "kvtupdatebook:App\\\Events\\\KVTBookUpdates";
    public static $evt_limitupdate        = "kvtupdatelimit:App\\\Events\\\KVTLimitUpdates";
    public static $evt_trdstatusupdate  = "wltradeupdate:App\\\Events\\\WLTradeStatusUpdate";
    public static $evt_marqueeupdate    = "kvtupdatemarquee:App\\\Events\\\KVTMarqueeUpdates";
    public static $evt_newsupdate        = "kvtupdatenews:App\\\Events\\\KVTNewsUpdates";
    public static $evt_textupdate         = "kvtupdatetext:App\\\Events\\\KVTTextUpdates";
    public static $evt_terminateuser    = "kvtupdateusertermination:App\\\Events\\\KVTUserUpdates";

    /** Notification Settings */
    public static $notification_title             = "KVT Jewellers";
    public static $notification_subtitle          = "From KVT Jewellers";
    public static $onesignalAPI                   = "https://onesignal.com/api/v1/notifications";
    public static $app_id                         = "";
    public static $onesignalauth                  = "";
    public static $notification_title_admin       = "KVT Jewellers Admin App";
    public static $notification_subtitle_admin     = "From KVT Jewellers Admin App";
    public static $app_id_admin                   = "";
    public static $onesingalapi_admin             = "";

    /** WhatsApp Configuration */
    public static $whatsappurl = "http://whatsappsms.creativepoint.in/api/";
    public static $instanceid  = "";

    /** Mobile App URLs */
    public static $androidUrl = "";
    public static $iosUrl     = "";

    /** Enquiry Email IDs */
    public static $enqFromId = "";
    public static $enqToId   = "";
    public static $enqCCId   = "";

    /** Book Number Placeholder */
    public static $bookno_for_mobile = '<i class="phone-portrait"></i><a class="sub-color" href="tel:+60"></a>';

    /** Timezone */
    public static $timezone = "Asia/Kuala_Lumpur";

    /** Motilal Oswal Hedge Configuration (Only for Indian Clients) */
    public static $clientcode = "";
    public static $hedge_password = "";
    public static $secret_key = "";
    public static $twoFA = "";
    public static $ApiKey = "";
    public static $authapi = "";
    public static $placeorder = "";
    public static $gold_mini_symbol = "";
    public static $gold_micro_symbol = "";

    /** Currency Configuration */
    public static $currency_symbol = "RM";
    public static $currency_name   = "MYR";
}

// Set default timezone
date_default_timezone_set(Globals::$timezone);

// Check cURL
if (!function_exists('curl_version')) {
    exit("Enable cURL in PHP to proceed...");
}
